name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configuration de Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Rendre le wrapper Gradle exécutable
        run: chmod +x gradlew

      - name: Vérification du code (Ktlint)
        run: ./gradlew ktlintCheck